name: ci

on:
  push:
    branches:
      - trunk

  pull_request:
    branches:
      - trunk

  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.TOX_ENV }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]
        TOX_ENV: ["lint", "py310", "mypy"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Tox Run
        run:  |
          pip install tox;
          TOX_ENV="${{ matrix.TOX_ENV }}";
          echo "Starting: ${TOX_ENV} ${PUSH_DOCS}"
          if [[ -n "${TOX_ENV}" ]]; then
            tox -e "$TOX_ENV";
          fi
